server:
  error:
    include-exception: false
    include-stacktrace: never
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db-parking
    driver-class-name: org.postgresql.Driver
    username: local.dev.001
    password: local.dev.001
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /api-docs
    supported-submit-methods: ["get", "post", "put", "delete"]

parking-value-setting:
  oneHourValue: 5.00
  additionalPerHourValue: 2.00
  dayValue: 20.00

app-security-in-memory:
  user:
    name: user
    password: user.001
    roles: USER