springdoc:
  swagger-ui:
    path: /doc
  api-docs:
    path: /parking/v1

server:
  error:
    include-exception: false
    include-stacktrace: never
    include-message: always

parking-value-setting:
  oneHourValue: 5.00
  additionalPerHourValue: 2.00
  dayValue: 20.00
